// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/vnnyx/gas-api/controller/user"
	"github.com/vnnyx/gas-api/infrastructure"
	user2 "github.com/vnnyx/gas-api/repository/user"
	user3 "github.com/vnnyx/gas-api/service/user"
)

// Injectors from wire.go:

func InitializeUserController(configName string) user.UserController {
	config := infrastructure.NewConfig(configName)
	db := infrastructure.NewMySQLDatabase(config)
	userRepository := user2.NewUserRepository(db)
	userService := user3.NewUserService(userRepository)
	userController := user.NewUserController(userService)
	return userController
}
